
name: Run unit and ui tests
on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby 3.3.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
          
      - Install dependencies
        run: |
          gem install bundler
          bundle install
    
      - name: Setup xcodegen and init xcode project
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          use-cache: true
          
      - name: Show environment info
        run: |
          xcodebuild -version
          fastlane --version
          ruby --version
          gem list | grep cocoapods

      - name: Run tests with fastlane
        run: bundle exec fastlane test
